domain_path: /opt/monutchee/project/kr260demo/KR260Demo_RPU/platform/export/platform/sw/freertos_psu_cortexr5_0
app_src_dir: /opt/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
